[package]
name = "UpWork_Job_Finder"
version = "0.1.0"
authors = ["Nick Vincent <emailnjv@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
